/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
 * Generated on: 06-Mar-2021 19:39:48
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 1
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\MATLAB\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 3
const int NL[MWSPT_NSEC] = { 1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9854966362737,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.970612877842,   0.9713736672526 
  },
  {
                   1,                 0,                 0 
  }
};
